apiVersion: v1
kind: Service
metadata:
  name: demo-service
  labels:
    k8s-app: demo-app
spec:
  type: LoadBalancer
  selector:
    k8s-app: demo-app
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
