---
apiVersion: v1
kind: ReplicationController
metadata:
  name: demo-app
  labels:
    k8s-app: demo-app
spec:
  replicas: 1
  selector:
    k8s-app: demo-app
  template:
    metadata:
      labels:
        k8s-app: demo-app
    spec:
      containers:
        - image: tazjin/log-courier:latest
          name: log-courier
          volumeMounts:
            - name: log-storage
              mountPath: /var/log/nginx
        - image: tazjin/nginx:latest
          name: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: log-storage
              mountPath: /var/log/nginx
            - name: www-storage
              mountPath: /usr/share/nginx/html
      volumes:
        - name: www-storage
          gitRepo:
            repository: https://github.com/tazjin/k8s-elk-demo.git
            revision: content-v1
        - name: log-storage
          emptyDir: {}
