apiVersion: v1
kind: Service
metadata:
  name: elk-svc
  labels:
    k8s-app: elk
spec:
  type: LoadBalancer
  selector:
    k8s-app: elk
  ports:
    - port: 8600
      name: logstash
    - port: 5601
      name: kibana
