apiVersion: v1
kind: ReplicationController
metadata:
  name: elk-rc
  labels:
    k8s-app: elk
spec:
  selector:
    k8s-app: elk
  template:
    metadata:
      labels:
        k8s-app: elk
    spec:
      containers:
        - image: eu.gcr.io/composite-watch-759/elasticsearch:latest
          name: elasticsearch
          ports:
            - containerPort: 9200
          volumeMounts:
            - name: es-storage
              mountPath: /usr/share/elasticsearch/data
        - image: eu.gcr.io/composite-watch-759/logstash:latest
          name: logstash
          ports:
            - containerPort: 8600
        - image: eu.gcr.io/composite-watch-759/kibana
          name: kibana
          env:
            - name: ELASTICSEARCH_URL
              value: http://127.0.0.1:9200
          ports:
            - containerPort: 5601
      volumes:
        - name: es-storage
          gcePersistentDisk:
            pdName: es-storage-v1
            fsType: ext4
